import { useState, useEffect, useCallback } from 'react';
import { TrendingUp, DollarSign, Layers, Search, ExternalLink, Info, RefreshCw } from 'lucide-react';
import { GoldRushClient } from '@covalenthq/client-sdk';

const SUPPORTED_CHAINS = [
  { name: 'Ethereum', id: 'eth-mainnet', icon: '⟠' },
  { name: 'Polygon', id: 'matic-mainnet', icon: '⬡' },
  { name: 'BSC', id: 'bsc-mainnet', icon: '◆' },
  { name: 'Arbitrum', id: 'arbitrum-mainnet', icon: '◉' },
  { name: 'Optimism', id: 'optimism-mainnet', icon: '◎' },
  { name: 'Base', id: 'base-mainnet', icon: '◈' },
  { name: 'Avalanche', id: 'avalanche-mainnet', icon: '▲' },
];

const MOCK_YIELD_OPPORTUNITIES = [
  {
    id: 1,
    protocol: 'Aave',
    chain: 'eth-mainnet',
    chainName: 'Ethereum',
    pool: 'USDC',
    apy: 4.25,
    tvl: 1250000000,
    risk: 'low',
    type: 'Lending',
    icon: '🏦',
  },
  {
    id: 2,
    protocol: 'Uniswap V3',
    chain: 'eth-mainnet',
    chainName: 'Ethereum',
    pool: 'ETH/USDC',
    apy: 12.8,
    tvl: 850000000,
    risk: 'medium',
    type: 'Liquidity Pool',
    icon: '🦄',
  },
  {
    id: 3,
    protocol: 'Curve',
    chain: 'eth-mainnet',
    chainName: 'Ethereum',
    pool: '3pool',
    apy: 3.5,
    tvl: 2100000000,
    risk: 'low',
    type: 'Stableswap',
    icon: '🌊',
  },
  {
    id: 4,
    protocol: 'PancakeSwap',
    chain: 'bsc-mainnet',
    chainName: 'BSC',
    pool: 'CAKE/BNB',
    apy: 45.2,
    tvl: 125000000,
    risk: 'high',
    type: 'Liquidity Pool',
    icon: '🥞',
  },
  {
    id: 5,
    protocol: 'QuickSwap',
    chain: 'matic-mainnet',
    chainName: 'Polygon',
    pool: 'MATIC/USDC',
    apy: 18.5,
    tvl: 95000000,
    risk: 'medium',
    type: 'Liquidity Pool',
    icon: '⚡',
  },
  {
    id: 6,
    protocol: 'Compound',
    chain: 'eth-mainnet',
    chainName: 'Ethereum',
    pool: 'DAI',
    apy: 3.8,
    tvl: 980000000,
    risk: 'low',
    type: 'Lending',
    icon: '🏛️',
  },
  {
    id: 7,
    protocol: 'GMX',
    chain: 'arbitrum-mainnet',
    chainName: 'Arbitrum',
    pool: 'GLP',
    apy: 28.5,
    tvl: 450000000,
    risk: 'medium',
    type: 'Perpetuals',
    icon: '📊',
  },
  {
    id: 8,
    protocol: 'Velodrome',
    chain: 'optimism-mainnet',
    chainName: 'Optimism',
    pool: 'OP/USDC',
    apy: 35.2,
    tvl: 78000000,
    risk: 'medium',
    type: 'Liquidity Pool',
    icon: '🚴',
  },
  {
    id: 9,
    protocol: 'Aerodrome',
    chain: 'base-mainnet',
    chainName: 'Base',
    pool: 'ETH/USDC',
    apy: 42.8,
    tvl: 156000000,
    risk: 'medium',
    type: 'Liquidity Pool',
    icon: '✈️',
  },
  {
    id: 10,
    protocol: 'Trader Joe',
    chain: 'avalanche-mainnet',
    chainName: 'Avalanche',
    pool: 'AVAX/USDC',
    apy: 22.4,
    tvl: 210000000,
    risk: 'medium',
    type: 'Liquidity Pool',
    icon: '☕',
  },
  {
    id: 11,
    protocol: 'Balancer',
    chain: 'eth-mainnet',
    chainName: 'Ethereum',
    pool: 'wstETH/WETH',
    apy: 8.9,
    tvl: 520000000,
    risk: 'low',
    type: 'Liquidity Pool',
    icon: '⚖️',
  },
  {
    id: 12,
    protocol: 'Stargate',
    chain: 'arbitrum-mainnet',
    chainName: 'Arbitrum',
    pool: 'USDC',
    apy: 6.2,
    tvl: 340000000,
    risk: 'low',
    type: 'Bridge Liquidity',
    icon: '🌉',
  },
];

const REFRESH_INTERVALS = [
  { label: '30s', value: 30000 },
  { label: '1m', value: 60000 },
  { label: '5m', value: 300000 },
  { label: '10m', value: 600000 },
];

